# SleepPlus 配置文件

# 睡眠百分比设置
# 当服务器中有这个百分比的玩家睡觉时，夜晚将被跳过
# 例如：设置为50时，如果服务器有10名玩家，则需要5名玩家睡觉
sleep-percentage: 50.0

# 睡眠超时跳过功能
# 当设置为true时，如果有玩家睡觉超过指定时间，即使没有达到所需百分比，也会跳过夜晚
enable-timeout-skip: true

# 睡眠超时时间（秒）
# 如果启用了睡眠超时功能，这里指定需要多少秒才会触发跳过夜晚
timeout-seconds: 30
